name: Moodle Plugin CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
        - 5432:5432
        # Health check to wait for postgres to start.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    env:
       DB: 'pgsql'
       DBHOST: 'postgres'
       MOODLE_BRANCH: 'master'
       TRAVIS_BUILD_DIR: $GITHUB_WORKSPACE
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: '7.3'
        extensions: mbstring, pgsql
        tools: phpunit

    - name: Deploy moodlehq/moodle-plugin-ci
      run: |
        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
        echo $(cd ci/bin; pwd) >> $GITHUB_PATH; echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH

    - name: Install moodle-plugin-ci
      run: moodle-plugin-ci install -vvv

