name: Moodle Plugin CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
        - 5432:5432
        # Health check to wait for postgres to start.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    env:
       DB: 'pgsql'
       DBHOST: 'postgres'
       # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
       MOODLE_BRANCH: 'master'
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        # Clone in plugin subdir, so we can setup CI in default directory.
        path: plugin

    - name: Install node
      uses: actions/setup-node@v1
      with:
        # TODO: Check if we can support .nvmrc
        node-version: '14.15.0'

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, pgsql
        tools: phpunit

    - name: Deploy moodle-plugin-ci
      run: |
        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
        # Add dirs to $PATH
        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
        # GITHUB_WORKSPACE is available after checkout action and reflects
        # default build directory. Set TRAVIS_BUILD_DIR to plugin clone, this
        # is where it will be copied from to moodle install.
        echo "TRAVIS_BUILD_DIR=${GITHUB_WORKSPACE}/plugin" >> $GITHUB_ENV
        # PHPUnit depends on en_AU.UTF-8 locale
        sudo locale-gen en_AU.UTF-8
        sudo update-locale

    - name: Install moodle-plugin-ci
      run: moodle-plugin-ci install -vvv

    - name: Run Integration tests
      run: |
        # Currently it stopes if any command return non 0 exist status, need
        # wrapper to collect exist status and list result and the end.
        # For testing purposes at this stage, just assume each command succeeds.
        moodle-plugin-ci phplint || true
        moodle-plugin-ci phpcpd || true
        moodle-plugin-ci phpmd || true
        moodle-plugin-ci codechecker || true
        moodle-plugin-ci validate || true
        moodle-plugin-ci savepoints || true
        moodle-plugin-ci mustache || true
        moodle-plugin-ci grunt || true
        moodle-plugin-ci phpdoc || true
        moodle-plugin-ci phpunit || true
        moodle-plugin-ci behat || true

